mfa.preferred=GoogleAuthenticator
mfa.redirectPath=/app/template/Index.vm
mfa.googleAuthenticator.qrCodeUrlTemplate=https://chart.googleapis.com/chart?chs=200x200&chld=M%%7C0&cht=qr&chl=otpauth://totp/MFA_ISSUER:MFA_USERNAME?secret=MFA_SECRET&issuer=MFA_ISSUER
mfa.googleAuthenticator.verificationPath=/app/template/MfaGoogleAuthenticatorVerify.vm
mfa.googleAuthenticator.registerPath=/app/template/MfaGoogleAuthenticatorRegister.vm
mfa.email.verificationPath=/app/template/MfaEmailVerify.vm
mfa.email.codeSentTextTemplate=/screens/OTPCodeSentByEmail.vm
mfa.sms.verificationPath=/app/template/MfaSMSVerify.vm
mfa.sms.codeSentTextTemplate=/screens/OTPCodeSentBySMS.vm