mfa.sms.amazon.sns.accesskey=ACCESS_KEY_HERE
mfa.sms.amazon.sns.secretaccesskey=SECRET_HERE
mfa.sms.amazon.sns.region=us-east1
mfa.sms.amazon.sns.senderid=SENDERID_HERE
mfa.sms.amazon.sns.smstype=Transactional