# Copyright 2019 Radiologics, Inc
# Developer: James Ransford ransfordj@radiologics.com
#            Mohana Ramaratnam (mohana@radiologics.com) 		

preferredSiteMfaPanel:
    kind: panel.form
    name: preferredSiteMfaPanel
    id: preferred-site-mfa
    label: "MFA Preferences"
    contents:
        config:
            tag: div#preferredSiteMfa-manager #dont change, see multifactorAuth-siteAdmin.js

mfaUserManagementPanel:
    kind: panel
    name: mfaUserManagementPanel
    label: "Manage MFA for Site Users"
    footer: false
    contents:
        info:
            tag: div.message
            element:
                style: "margin: 0 0 1rem"
            contents: "Manage users' MFA registration individually using the table below. You can reset their MFA registration, which will revert their MFA method to the site default and give them an opportunity to re-enroll, or mark a user exempt from the MFA requirement. <br><br><button class='btn btn-sm reset-mfa-for-all-users'><i class='fa fa-refresh'></i>&nbsp; Reset All Users</button>"
        config:
            tag: div#mfa-exempt-users.data-table-container #dont change, see multifactorAuth-siteAdmin.js
            
mfaSettingsFormPanel:
    kind: panel.form
    name: mfaSettingsFormPanel
    id: mfa-settings-form
    label: "MFA Site Configuration"
    contents:
        siteAdminScripts:
            tag: script|src="~/scripts/mfa/multifactorAuth-siteAdmin.js"
        require_mfa:
            kind: panel.input.switchbox
            name: requireMfa
            id: requireMfa
            label: Require MFA for Non-admins
            description: Require Multifactor Authentication to be enabled on all non admin accounts.
        require_admin_mfa:
            kind: panel.input.switchbox
            name: requireAdminMfa
            id: requireAdminMfa
            className: "checkAdminStatus requireMfaAdmin"
            label: Require MFA for Administrators
            description: Require Multifactor Authentication to be enabled on Admin accounts. 
        config:
           tag: div#mfa-siteConfig-manager #dont change, see multifactorAuth-siteAdmin.js

mfaSettingsTab:
    kind: tab
    name: mfaSettingsTab
    label: MFA Settings
    group: mfaTabGroup
    contents:
        ${mfaSettingsFormPanel}
        ${preferredSiteMfaPanel}

mfaUserManagementTab:
    kind: tab
    name: mfaUserManagementTab
    label: MFA User Management
    group: mfaTabGroup
    contents:
        ${mfaUserManagementPanel}

# Group these settings with other XNAT CR feature settings
siteSettings:
    kind: tabs
    name:  mfaAdmin
    label: Multifactor Authentication
    meta:
        tabGroups:
            mfaTabGroup: MFA Settings
    contains: tabs
    tabs: 
        ${mfaSettingsTab}
        ${mfaUserManagementTab}